name: Release

on:
  push:
    tags: ["*"]

permissions:
  contents: write

jobs:
  release:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: "~> v2"
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAP_GITHUB_TOKEN: ${{ secrets.TAP_GITHUB_TOKEN }}
brews:
  - name: tmux-sessionizer
    tap:
      owner: TlexCypher
      name: homebrew-tap
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/TlexCypher/tmux-sessionizer"

